# -*- coding: utf-8 -*-
"""up2286718.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12IiztfBp48vnxHX7tJ9zoK8XKg2Bmmac
"""

!pip install yt-dlp
!pip install pytube moviepy
!pip install webrtcvad soundfile
!pip install transformers
!pip install torch
!pip install transformers datasets librosa
!apt-get update
!apt-get install -y ffmpeg
!pip install torchcodec
!pip install gradio

# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This is a generated file!  Do not edit.

with open("cookies.txt", "w") as f:
    f.write("""# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This is a generated file!  Do not edit.

.youtube.com	TRUE	/	TRUE	1762179665	__Secure-YEC	CgtRUkZqVWlFQVFKRSjR8_-3BjIKCgJHQhIEGgAgQg%3D%3D
.youtube.com	TRUE	/	TRUE	1762179818	SOCS	CAISFggDEgk2ODE2MjA0MzYaBWVuLUlOIAEaBgiA4Py3Bg
.youtube.com	TRUE	/	TRUE	1762611819	LOGIN_INFO	AFmmF2swRQIhAKgH06sITeLmp5RhgF9lViQQX-7Xr5PWlvtss80fjlbDAiA7N2rv9Td4zimBA6IUaI2m51wA2xQMUIpqrXIGtv61CA:QUQ3MjNmeHh2SUdWcU5qQnIzVVZPblk2ZVpsSmtQWlpidjlCcWVJOEJqWTZndXlEbFdtWDVpZ3JzTG5tcG0wME9ZQk1JLTZUakpJQXljMmpBcUp5Vy1jY093MndyU0J0X3RVZy1DeG02a0dSU1VGcTFXUkRCSnR0QjVxQWpLel81NFJRTWhaSHp4V0Zid0JjT05PQ1R0c2tSYjJ5ajNmWWd3
.youtube.com	TRUE	/	TRUE	1787232541	PREF	f6=40000080&f7=4150&tz=Asia.Calcutta&f5=20000&f4=4000000
.youtube.com	TRUE	/	FALSE	1786988684	SID	g.a000zAiktiQNV-msYNFu6nTLMJ5S6isBCRUGTCOkccZrZvoRn5Q8QrwKV3eVlvIuurmVXwckOAACgYKAfcSARESFQHGX2MikjNyPUQgMmoyYnapO7NjJBoVAUF8yKrHKxorUjMyy9vFZ0qP4cRH0076
.youtube.com	TRUE	/	TRUE	1786988684	__Secure-1PSID	g.a000zAiktiQNV-msYNFu6nTLMJ5S6isBCRUGTCOkccZrZvoRn5Q8bzR-Q1b1gmVpJQIp8QOexAACgYKAccSARESFQHGX2MifQrDQcZ9uWlb-EnKNi0OaBoVAUF8yKpPoJZ2DwIWHjVSV3APXWha0076
.youtube.com	TRUE	/	TRUE	1786988684	__Secure-3PSID	g.a000zAiktiQNV-msYNFu6nTLMJ5S6isBCRUGTCOkccZrZvoRn5Q8pYB3ycqdqAZWby4FqwPMpAACgYKAZgSARESFQHGX2MiL-h4XO3Koi4iJ5XRpqD97xoVAUF8yKr2VwC66cj8nH_uT9DQTUKX0076
.youtube.com	TRUE	/	FALSE	1786988684	HSID	AiOS0njRa63GlylNi
.youtube.com	TRUE	/	TRUE	1786988684	SSID	AzqpFLtxzx74qeFLg
.youtube.com	TRUE	/	FALSE	1786988684	APISID	CFTEJj_4WkM5TGDY/AtLtfHVTq_8ReCwhr
.youtube.com	TRUE	/	TRUE	1786988684	SAPISID	1QDqGq_8pSC0qYS-/AFOC8R8j6qiiLCxfL
.youtube.com	TRUE	/	TRUE	1786988684	__Secure-1PAPISID	1QDqGq_8pSC0qYS-/AFOC8R8j6qiiLCxfL
.youtube.com	TRUE	/	TRUE	1786988684	__Secure-3PAPISID	1QDqGq_8pSC0qYS-/AFOC8R8j6qiiLCxfL
.youtube.com	TRUE	/	TRUE	1784208636	__Secure-1PSIDTS	sidts-CjEB5H03P7KoG4-EO-QuR-IQnRpLuz3LknYPYKW4VSNYXUKfcrjfJTDoloTgJlPc_ePgEAA
.youtube.com	TRUE	/	TRUE	1784208636	__Secure-3PSIDTS	sidts-CjEB5H03P7KoG4-EO-QuR-IQnRpLuz3LknYPYKW4VSNYXUKfcrjfJTDoloTgJlPc_ePgEAA
.youtube.com	TRUE	/	FALSE	1784208861	SIDCC	AKEyXzWkaK7dqsU72RRpYsEjQxchFZ_XiEEFV4HsXhg3Ci4OW61_yL_tB64JlFcmZpjtX8UOtSLu
.youtube.com	TRUE	/	TRUE	1784208861	__Secure-1PSIDCC	AKEyXzUuTkzSkyp44zYKAfqd3zpZwUuJej8y4zl7WvtoxUBpLHqBOriAfeFwIU7vNfI-ezmDyv7z
.youtube.com	TRUE	/	TRUE	1784208861	__Secure-3PSIDCC	AKEyXzWD2ZZM7Qm5T7fk1Z-HobFJBOGSeDbbB_e7BXSDT7Ma8SFIzOjZx0oQA_46BVn8kEgUUJE
.youtube.com	TRUE	/	TRUE	1768224185	VISITOR_INFO1_LIVE	SbzEPeGZ1qA
.youtube.com	TRUE	/	TRUE	1768224185	VISITOR_PRIVACY_METADATA	CgJJThIEGgAgQg%3D%3D
.youtube.com	TRUE	/	TRUE	1756587496	__Secure-ROLLOUT_TOKEN	CK3a6IObr_bcgQEQlL6_0ubuiwMYlL6_0ubuiwM%3D
.youtube.com	TRUE	/	TRUE	1756587496	VISITOR_INFO1_LIVE	Km0mo2F7aHI
.youtube.com	TRUE	/	TRUE	1756587496	VISITOR_PRIVACY_METADATA	CgJHQhIEGgAgZQ%3D%3D
.youtube.com	TRUE	/	TRUE	0	YSC	oAYrcKDnspM
.youtube.com	TRUE	/	TRUE	1768153616	__Secure-ROLLOUT_TOKEN	CLyB8-vm4L39IRC564ff4-uKAxiIjsHntb-OAw%3D%3D
""")

# ─── SETUP DRIVE ────────────────────────────────────────────────────────────────
from google.colab import drive
drive.mount('/content/drive')

# ─── IMPORTS ─────────────────────────────────────────────────────────────────────
import os
import glob
import csv
import subprocess
from concurrent.futures import ThreadPoolExecutor
import time
import random
import numpy as np
import torch
import yt_dlp
import soundfile as sf
import webrtcvad
from transformers import pipeline

# ─── CONFIGURATION ───────────────────────────────────────────────────────────────

video_urls = [
    "https://www.youtube.com/watch?v=Yy6kbVptkRY",
    "https://www.youtube.com/watch?v=7LD8iC4NqXM",
    "https://www.youtube.com/watch?v=JKUFWK6iSsw",
    "https://www.youtube.com/watch?v=sDrakgSYvzc",
    "https://www.youtube.com/watch?v=8aDFvvjC6XM",
    "https://www.youtube.com/watch?v=9cYeZdKeXsc",
    "https://www.youtube.com/watch?v=ciaoqPxyD_Q",
    "https://www.youtube.com/watch?v=SNstOn6owcI",
    "https://www.youtube.com/watch?v=j1mehpweq4g",
    "https://www.youtube.com/watch?v=ZDpMz864zBA",
    "https://www.youtube.com/watch?v=82YC8jm6x-Q",
    "https://www.youtube.com/watch?v=PeuPLVlhAiM",
    "https://www.youtube.com/watch?v=wPREXk_zCu4",
    "https://www.youtube.com/watch?v=XH2tF8oB3cw",
    "https://www.youtube.com/watch?v=W3hMmZQAdhw",
    "https://www.youtube.com/watch?v=tlQHg2Rbm60",
    "https://www.youtube.com/watch?v=HKJXCj1xPH0",
    "https://www.youtube.com/watch?v=7De6VY8P9hY",
    "https://www.youtube.com/watch?v=gbBn8EzZx3w",
    "https://www.youtube.com/watch?v=8K4HW6_MvoU",
    "https://www.youtube.com/watch?v=gcXENqOwulw",
    "https://www.youtube.com/watch?v=LuuKIF4-F_Q",
    "https://www.youtube.com/watch?v=o2Cv6Mlp3KY",
    "https://www.youtube.com/watch?v=TcewFGydzPM",
    "https://www.youtube.com/watch?v=mpE-oaix5kA",
    "https://www.youtube.com/watch?v=UkjjYbFBctk",
    "https://www.youtube.com/watch?v=VllviqjGYpw",
    "https://www.youtube.com/watch?v=BYbCvD_8QYE",
    "https://www.youtube.com/watch?v=cgfs3h6Ahe8",
]

BASE_DIR = "/content/drive/MyDrive/Youtube_Emotion_Project"
DOWNLOAD_DIR = os.path.join(BASE_DIR, "downloaded_videos")
AUDIO_DIR    = os.path.join(BASE_DIR, "audio_segments")
os.makedirs(DOWNLOAD_DIR, exist_ok=True)
os.makedirs(AUDIO_DIR, exist_ok=True)

segment_seconds = 20  # <-- Try 40s chunks for higher emotion confidence

# ─── HELPERS ─────────────────────────────────────────────────────────────────────

def run(cmd):
    proc = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    return proc.returncode, proc.stdout, proc.stderr

def get_duration(path):
    rc, out, _ = run([
        "ffprobe", "-v", "error",
        "-show_entries", "format=duration",
        "-of", "default=noprint_wrappers=1:nokey=1",
        path
    ])
    return float(out.strip()) if rc == 0 and out.strip() else 0.0

# ─── STEP 1: DOWNLOAD VIDEOS ─────────────────────────────────────────────────────

RE_DOWNLOAD = False

def download_video(idx, url):
    out = os.path.join(DOWNLOAD_DIR, f"video_{idx+1}.mp4")
    if not RE_DOWNLOAD and os.path.exists(out) and os.path.getsize(out) > 100_000:
        return out

    ydl_opts = {
        'format': 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4',
        'extractor_retries': 5,
        'outtmpl': out,
        'merge_output_format': 'mp4',
        # 'cookies_from_browser': ('chrome',),
        'cookiefile': '/content/cookies.txt',
        'sleep_interval': 10,
        'max_sleep_interval': 30,
        'retries': 10,
        'ratelimit': 1_000_000,
        'http_headers': {
            'User-Agent': (
                'Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
                'AppleWebKit/537.36 (KHTML, like Gecko) '
                'Chrome/115.0.0.0 Safari/537.36'
            )
        },
    }

    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            ydl.download([url])
        time.sleep(random.uniform(5, 15))
        return out if os.path.exists(out) else None
    except Exception as e:
        print(f"❌ Download failed for {url}: {e}")
        return None

with ThreadPoolExecutor(max_workers=1) as exe:
    videos = list(exe.map(download_video, range(len(video_urls)), video_urls))

videos = [v for v in videos if v]
if not videos:
    print("🚫 No videos downloaded; exiting.")
    exit()

print(f"✅ Downloaded {len(videos)} videos (skipped failures).")

# ─── STEP 2: EXTRACT AUDIO & SEGMENT ─────────────────────────────────────────────

def extract_full_audio(video_path, audio_path):
    cmd = [
        "ffmpeg", "-y", "-i", video_path,
        "-map", "0:a:0?",  # first audio stream if present
        "-ac", "1", "-ar", "16000",
        "-c:a", "pcm_s16le",
        "-f", "wav",
        audio_path
    ]
    rc, out, err = run(cmd)
    if rc != 0 or not os.path.exists(audio_path) or os.path.getsize(audio_path) < 1024:
        print(f"❌ Full audio extraction failed for {os.path.basename(video_path)}: {err.strip()}")
        return None
    try:
        info = sf.info(audio_path)
        if info.channels != 1 or info.samplerate != 16000:
            raise ValueError("Not mono or not 16kHz")
    except Exception as e:
        print(f"⚠️ Extracted audio not valid: {audio_path} ({e})")
        if os.path.exists(audio_path):
            os.remove(audio_path)
        return None
    return audio_path

def denoise_audio(input_wav, output_wav):

    cmd = [
        "ffmpeg", "-y", "-i", input_wav,
        "-af", "afftdn",
        "-ar", "16000", "-ac", "1",
        "-c:a", "pcm_s16le",
        output_wav
    ]
    rc, _, err = run(cmd)
    if rc != 0:
        print(f"❌ Denoising failed for {input_wav}: {err.strip()}")
        return None
    return output_wav

def segment_audio(audio_path, idx):
    try:
        info = sf.info(audio_path)
        duration = info.frames / info.samplerate
    except Exception as e:
        print(f"⚠️ Could not read audio info: {audio_path} ({e})")
        return []
    out = []
    for start in range(0, int(duration), segment_seconds):
        seg_path = os.path.join(AUDIO_DIR, f"video{idx+1}_{start:04d}.wav")
        cmd = [
            "ffmpeg", "-y",
            "-ss", str(start), "-t", str(segment_seconds),
            "-i", audio_path,
            "-acodec", "pcm_s16le",
            "-ar", "16000", "-ac", "1",
            "-map_metadata", "-1",
            "-f", "wav",
            seg_path
        ]
        rc, _, err = run(cmd)
        # Denoise segment
        denoised_path = seg_path.replace(".wav", "_denoise.wav")
        if rc == 0 and os.path.exists(seg_path) and os.path.getsize(seg_path) > 1024:
            denoised = denoise_audio(seg_path, denoised_path)
            if not denoised:
                continue
            # Validate with soundfile and np
            try:
                info = sf.info(denoised)
                data, _ = sf.read(denoised, dtype="int16")
                if data.ndim > 1:
                    data = data[:, 0]
                if np.abs(data).max() == 0 or np.mean(np.abs(data)) < 10:
                    print(f"⚠️ Skipping silent segment {denoised}")
                    os.remove(denoised)
                    continue
                out.append(denoised)
            except Exception as ex:
                print(f"⚠️ Invalid audio segment {denoised}: {ex}")
                if os.path.exists(denoised):
                    os.remove(denoised)
        else:
            print(f"❌ Audio segment failed at {start}s for {os.path.basename(audio_path)}: {err.strip()}")
    if not out:
        print(f"⚠️ No valid segments for {audio_path}")
    return out

def extract_and_segment_all(videos):
    audio_paths = []
    all_segments = []
    for idx, video_path in enumerate(videos):
        audio_path = os.path.join(AUDIO_DIR, f"video{idx+1}_full.wav")
        if extract_full_audio(video_path, audio_path):
            audio_paths.append(audio_path)
            segments = segment_audio(audio_path, idx)
            all_segments.extend(segments)
    return all_segments

raw_segments = extract_and_segment_all(videos)
print(f"Retained {len(raw_segments)} valid audio segments.")

# ─── STEP 3: EMOTION DETECTION ───────────────────────────────────────────────────


model_name = "superb/wav2vec2-base-superb-er"

device = 0 if torch.cuda.is_available() else -1
emotion_pipeline = pipeline(
    "audio-classification",
    model=model_name,
    top_k=1,
    device=device
)

results = []
batch_size = 8
for i in range(0, len(raw_segments), batch_size):
    batch = raw_segments[i:i+batch_size]
    try:
        outs = emotion_pipeline(batch)
        for path, out in zip(batch, outs):
            if isinstance(out, list):
                out = out[0]
            results.append({
                "clip": os.path.basename(path),
                "emotion": out["label"],
                "confidence": round(out["score"], 3)
            })
            print(f"🎧 {os.path.basename(path)}: {out['label']} ({round(out['score'],3)})")
    except Exception as e:
        print(f"⚠️ Batch {i}-{i+batch_size} failed: {e}")
        for path in batch:
            results.append({"clip": os.path.basename(path), "emotion": "error", "confidence": 0.0})

# --- STEP 4: SAVE RESULTS ------------------------------------------------------

results_path = os.path.join(BASE_DIR, "results.csv")
with open(results_path, "w", newline="") as f:
    writer = csv.DictWriter(f, fieldnames=["clip", "emotion", "confidence"])
    writer.writeheader()
    writer.writerows(results)

print(f"✅ Done. Results saved to {results_path}")

pip install yt-dlp openai-whisper transformers torch ffmpeg-python

"""Summary

1. Facebook Wav2Vec2-Base
"""

!pip install -U transformers datasets accelerate

# --- 1. IMPORTS & SETUP ---
from google.colab import drive
drive.mount('/content/drive')

import os
import pandas as pd
import numpy as np
import torch
from datasets import Dataset
from transformers import (
    Wav2Vec2ForSequenceClassification,
    Wav2Vec2FeatureExtractor,
    TrainingArguments,
    Trainer,
    TrainerCallback
)
from sklearn.metrics import (
    classification_report, accuracy_score, confusion_matrix,
    ConfusionMatrixDisplay, f1_score, precision_score, recall_score
)
from sklearn.utils.class_weight import compute_class_weight
import librosa
import matplotlib.pyplot as plt
import torch.nn.functional as F
from IPython.display import Audio, display

os.environ["WANDB_DISABLED"] = "true"

# Paths
BASE_DIR = "/content/drive/MyDrive/Youtube_Emotion_Project"
AUDIO_DIR = os.path.join(BASE_DIR, "audio_segments")
CSV_PATH = os.path.join(BASE_DIR, "results.csv")

# Count audio files
audio_extensions = (".wav", ".mp3", ".flac", ".ogg", ".m4a")
num_clips = sum(1 for f in os.listdir(AUDIO_DIR) if f.lower().endswith(audio_extensions))
print(f"Number of clips in {AUDIO_DIR}: {num_clips}")

# --- 2. LOAD DATA ---
df = pd.read_csv(CSV_PATH)
df = df[df['confidence'] > 0.5].reset_index(drop=True)
df['path'] = df['clip'].apply(lambda x: os.path.join(AUDIO_DIR, x))
df = df[df['path'].apply(os.path.exists)]

emotions = sorted(df['emotion'].unique())
label2id = {label: i for i, label in enumerate(emotions)}
id2label = {i: label for label, i in label2id.items()}
df['label'] = df['emotion'].map(label2id)

print(f"Dataset size after filtering: {len(df)} samples")
print("Emotions:", emotions)

# --- 3. EXPLORATORY DATA ANALYSIS ---
plt.figure(figsize=(8,5))
plt.hist(df['confidence'], bins=20, color='skyblue', edgecolor='black')
plt.title("Distribution of Confidence Scores")
plt.xlabel("Confidence Score")
plt.ylabel("Frequency")
plt.show()

plt.figure(figsize=(8,5))
df['emotion'].value_counts().plot(kind='bar', color='lightgreen', edgecolor='black')
plt.title("Number of Audio Clips per Emotion")
plt.xlabel("Emotion")
plt.ylabel("Count of Clips")
plt.xticks(rotation=45)
plt.show()

# --- 4. DATASET PREPARATION ---
dataset = Dataset.from_pandas(df[['path', 'label']])
dataset = dataset.train_test_split(test_size=0.2, seed=42)

feature_extractor = Wav2Vec2FeatureExtractor.from_pretrained("facebook/wav2vec2-base")

def preprocess(batch):
    audio_array, _ = librosa.load(batch["path"], sr=16000)
    features = feature_extractor(
        audio_array,
        sampling_rate=16000,
        padding="max_length",
        max_length=int(16000*15),  # 20 sec max
        truncation=True,
        return_attention_mask=True,
        return_tensors="pt"
    )
    batch["input_values"] = features["input_values"][0]
    batch["labels"] = batch["label"]
    if "attention_mask" in features:
        batch["attention_mask"] = features["attention_mask"][0]
    return batch


dataset_prep = dataset.map(preprocess, remove_columns=dataset["train"].column_names)

# --- 5. MODEL SETUP ---
model = Wav2Vec2ForSequenceClassification.from_pretrained(
    "facebook/wav2vec2-base",
    num_labels=len(emotions),
    label2id=label2id,
    id2label=id2label,
)

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(df['label']),
    y=df['label']
)
class_weights = torch.tensor(class_weights, dtype=torch.float).to(model.device)
print("Class Weights:", class_weights)


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
class_weights = class_weights.to(device)

class WeightedTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, num_items_in_batch= None):
        labels = inputs.pop("labels")
        outputs = model(**inputs)
        logits = outputs.logits

        loss = F.cross_entropy(logits, labels, weight=class_weights)

        return (loss, outputs) if return_outputs else loss



def compute_metrics(pred):
    logits, labels = pred
    preds = np.argmax(logits, axis=1)
    acc = accuracy_score(labels, preds)
    f1 = f1_score(labels, preds, average='macro')
    precision = precision_score(labels, preds, average='macro')
    recall = recall_score(labels, preds, average='macro')
    return {
        'accuracy': acc,
        'macro_f1': f1,
        'macro_precision': precision,
        'macro_recall': recall
    }

# --- 6. TRAINING ARGUMENTS ---
training_args = TrainingArguments(
    output_dir=os.path.join(BASE_DIR, "finetuned_wav2vec2_base"),
    per_device_train_batch_size=2,
    num_train_epochs=3,
    learning_rate=1e-5,
    weight_decay=0.01,
    eval_strategy="steps",
    save_strategy="steps",
    save_steps=250,
    eval_steps=250,
    logging_steps=250,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    disable_tqdm=False,
    per_device_eval_batch_size=1,
    fp16=True,
    eval_accumulation_steps=8,

)

trainer = WeightedTrainer(
    model=model,
    args=training_args,
    train_dataset=dataset_prep['train'],
    eval_dataset=dataset_prep['test'],
    tokenizer=feature_extractor,
    compute_metrics=compute_metrics
)

# --- 7. CUSTOM CALLBACK FOR TRAIN ACCURACY ---
class TrainMetricsCallback(TrainerCallback):
    def __init__(self, trainer, dataset_prep, eval_subset_size=100):
        self.trainer = trainer

        self.train_subset = dataset_prep['train'].select(
            range(min(eval_subset_size, len(dataset_prep['train'])))
        )

    def on_log(self, args, state, control, logs=None, **kwargs):
        if logs is None or "loss" not in logs:
            return


        predictions = self.trainer.predict(self.train_subset)
        logits = predictions.predictions
        if isinstance(logits, tuple):
            logits = logits[0]
        y_pred = np.argmax(logits, axis=1)
        y_true = predictions.label_ids
        acc = (y_pred == y_true).mean()


        logs["training_accuracy"] = acc
        print(f"Step {state.global_step}: "
              f"Train Loss {logs['loss']:.4f} | Train Acc {acc:.4f}")

        self.trainer.state.log_history.append({**logs, "step": state.global_step})

trainer.add_callback(TrainMetricsCallback(trainer, dataset_prep))

# --- 8. TRAIN MODEL ---
trainer.train()

# --- 9. LOGS --- num_items_in_batch
logs = pd.DataFrame(trainer.state.log_history)
if not logs.empty:
    print("\nTraining Logs:")
    print(logs[['step', 'loss', 'eval_loss', 'training_accuracy', 'eval_accuracy']])
else:
    print("No logs were recorded.")

# --- 10. EVALUATION ---
preds = trainer.predict(dataset_prep['test'])
logits = preds.predictions
if isinstance(logits, (tuple, list)):
    logits = logits[0]
if logits.ndim > 2:
    logits = logits.squeeze()
y_pred = np.argmax(logits, axis=1)
y_true = preds.label_ids

report = classification_report(y_true, y_pred, target_names=emotions, digits=3)
print("\nClassification Report:\n", report)

# Confusion Matrix
cm = confusion_matrix(y_true, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=emotions)
disp.plot(xticks_rotation=45)
plt.title("Confusion Matrix")
plt.show()

# --- 11. CONFIDENCE DISTRIBUTION FOR PREDICTIONS ---
probs = F.softmax(torch.tensor(logits), dim=1).numpy()
conf_correct = [max(probs[i]) for i in range(len(y_true)) if y_true[i] == y_pred[i]]
conf_wrong = [max(probs[i]) for i in range(len(y_true)) if y_true[i] != y_pred[i]]

plt.hist(conf_correct, bins=20, alpha=0.7, label='Correct')
plt.hist(conf_wrong, bins=20, alpha=0.7, label='Incorrect')
plt.xlabel("Confidence")
plt.ylabel("Frequency")
plt.title("Confidence Distribution")
plt.legend()
plt.show()

"""2. ehcalabres/wav2vec2-lg-xlsr-en-speech-emotion-recognition"""

# --- SETUP DRIVE ---
from google.colab import drive
drive.mount('/content/drive')

import os
import pandas as pd
import numpy as np
import torch
from datasets import Dataset
from transformers import (
    Wav2Vec2ForSequenceClassification,
    Wav2Vec2FeatureExtractor,
    TrainingArguments,
    Trainer,
    EarlyStoppingCallback,
    TrainerCallback
)
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay, accuracy_score
import librosa
import matplotlib.pyplot as plt
import torch.nn.functional as F
from IPython.display import Audio, display
from sklearn.metrics import f1_score, precision_score, recall_score
from sklearn.utils.class_weight import compute_class_weight

os.environ["WANDB_DISABLED"] = "true"
BASE_DIR = "/content/drive/MyDrive/Youtube_Emotion_Project"
AUDIO_DIR = os.path.join(BASE_DIR, "audio_segments")
CSV_PATH = os.path.join(BASE_DIR, "results.csv")

# --- LOAD DATA ---
df = pd.read_csv(CSV_PATH)
df = df[df['confidence'] > 0.5].reset_index(drop=True)
df['path'] = df['clip'].apply(lambda x: os.path.join(AUDIO_DIR, x))
df = df[df['path'].apply(os.path.exists)]

emotions = sorted(df['emotion'].unique())
label2id = {label: i for i, label in enumerate(emotions)}
id2label = {i: label for label, i in label2id.items()}
df['label'] = df['emotion'].map(label2id)

dataset = Dataset.from_pandas(df[['path', 'label']]).train_test_split(test_size=0.2, seed=42)

# --- FEATURE EXTRACTION ---
feature_extractor = Wav2Vec2FeatureExtractor.from_pretrained(
    "ehcalabres/wav2vec2-lg-xlsr-en-speech-emotion-recognition"
)

def preprocess(batch):
    audio_array, _ = librosa.load(batch["path"], sr=16000)
    features = feature_extractor(
        audio_array,
        sampling_rate=16000,
        padding="max_length",
        max_length=int(16000*15),
        truncation=True,
        return_attention_mask=True,
        return_tensors="pt"
    )
    batch["input_values"] = features["input_values"][0]
    batch["labels"] = batch["label"]
    if "attention_mask" in features:
        batch["attention_mask"] = features["attention_mask"][0]
    return batch


dataset_prep = dataset.map(preprocess, remove_columns=dataset["train"].column_names)

# --- MODEL ---
model = Wav2Vec2ForSequenceClassification.from_pretrained(
    "ehcalabres/wav2vec2-lg-xlsr-en-speech-emotion-recognition",
    num_labels=len(emotions),
    label2id=label2id,
    id2label=id2label,
)

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(df['label']),
    y=df['label']
)
class_weights = torch.tensor(class_weights, dtype=torch.float).to(model.device)
print("Class Weights:", class_weights)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
class_weights = class_weights.to(device)

class WeightedTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, num_items_in_batch= None):
        labels = inputs.pop("labels")
        outputs = model(**inputs)
        logits = outputs.logits


        loss = F.cross_entropy(logits, labels, weight=class_weights)

        return (loss, outputs) if return_outputs else loss

# Metrics function
def compute_metrics(pred):
    logits, labels = pred
    preds = np.argmax(logits, axis=1)
    acc = accuracy_score(labels, preds)
    f1 = f1_score(labels, preds, average='macro')
    precision = precision_score(labels, preds, average='macro')
    recall = recall_score(labels, preds, average='macro')
    return {
        'accuracy': acc,
        'macro_f1': f1,
        'macro_precision': precision,
        'macro_recall': recall
    }
# --- TRAINING ARGS ---
training_args = TrainingArguments(
    output_dir=os.path.join(BASE_DIR, "finetuned_wav2vec2_emotion"),
    per_device_train_batch_size=2,
    num_train_epochs=3,
    learning_rate=1e-5,
    weight_decay=0.01,
    eval_strategy="steps",
    save_strategy="steps",
    save_steps=250,
    eval_steps=250,
    logging_steps=250,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    disable_tqdm=False,
    per_device_eval_batch_size=1,
    fp16=True,
    eval_accumulation_steps=8,

)

trainer = WeightedTrainer(
    model=model,
    args=training_args,
    train_dataset=dataset_prep['train'],
    eval_dataset=dataset_prep['test'],
    tokenizer=feature_extractor,
    compute_metrics=compute_metrics
)

# --- 7. CUSTOM CALLBACK FOR TRAIN ACCURACY ---
class TrainMetricsCallback(TrainerCallback):
    def __init__(self, trainer, dataset_prep, eval_subset_size=100):
        self.trainer = trainer

        self.train_subset = dataset_prep['train'].select(
            range(min(eval_subset_size, len(dataset_prep['train'])))
        )

    def on_log(self, args, state, control, logs=None, **kwargs):
        if logs is None or "loss" not in logs:
            return


        predictions = self.trainer.predict(self.train_subset)
        logits = predictions.predictions
        if isinstance(logits, tuple):
            logits = logits[0]
        y_pred = np.argmax(logits, axis=1)
        y_true = predictions.label_ids
        acc = (y_pred == y_true).mean()


        logs["training_accuracy"] = acc
        print(f"Step {state.global_step}: "
              f"Train Loss {logs['loss']:.4f} | Train Acc {acc:.4f}")


        self.trainer.state.log_history.append({**logs, "step": state.global_step})


trainer.add_callback(TrainMetricsCallback(trainer, dataset_prep))

trainer.add_callback(EarlyStoppingCallback(early_stopping_patience=2))

# --- 8. TRAIN MODEL ---
trainer.train()

# --- 9. LOGS ---
logs = pd.DataFrame(trainer.state.log_history)
if not logs.empty:
    print("\nTraining Logs:")
    print(logs[['step', 'loss', 'eval_loss', 'training_accuracy', 'eval_accuracy']])
else:
    print("No logs were recorded.")


logs = pd.DataFrame(trainer.state.log_history)
print(logs.head(20))

# --- PLOT TRAINING VS VALIDATION LOSS & ACCURACY ---
logs = pd.DataFrame(trainer.state.log_history)


# --- 10. EVALUATION ---
preds = trainer.predict(dataset_prep['test'])
logits = preds.predictions
if isinstance(logits, (tuple, list)):
    logits = logits[0]
if logits.ndim > 2:
    logits = logits.squeeze()
y_pred = np.argmax(logits, axis=1)
y_true = preds.label_ids

report = classification_report(y_true, y_pred, target_names=emotions, digits=3)
print("\nClassification Report:\n", report)

# Confusion Matrix
cm = confusion_matrix(y_true, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=emotions)
disp.plot(xticks_rotation=45)
plt.title("Confusion Matrix")
plt.show()


# --- 12. CONFIDENCE DISTRIBUTION FOR PREDICTIONS ---
probs = F.softmax(torch.tensor(logits), dim=1).numpy()
conf_correct = [max(probs[i]) for i in range(len(y_true)) if y_true[i] == y_pred[i]]
conf_wrong = [max(probs[i]) for i in range(len(y_true)) if y_true[i] != y_pred[i]]

plt.hist(conf_correct, bins=20, alpha=0.7, label='Correct')
plt.hist(conf_wrong, bins=20, alpha=0.7, label='Incorrect')
plt.xlabel("Confidence")
plt.ylabel("Frequency")
plt.title("Confidence Distribution")
plt.legend()
plt.show()

"""3. superb/superb/hubert-base-superb-er

"""

# --- 1. SETUP DRIVE ---
from google.colab import drive
drive.mount('/content/drive')

import os
import pandas as pd
import numpy as np
import torch
from datasets import Dataset
from transformers import (
    HubertForSequenceClassification,
    Wav2Vec2FeatureExtractor,
    TrainingArguments,
    Trainer,
    EarlyStoppingCallback,
    TrainerCallback
)
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay,
    accuracy_score
)
import librosa
import matplotlib.pyplot as plt
import torch.nn.functional as F
from sklearn.utils.class_weight import compute_class_weight
import gc
import torch

gc.collect()
torch.cuda.empty_cache()


os.environ["WANDB_DISABLED"] = "true"

# --- 2. PATHS ---
BASE_DIR = "/content/drive/MyDrive/Youtube_Emotion_Project"
AUDIO_DIR = os.path.join(BASE_DIR, "audio_segments")
CSV_PATH = os.path.join(BASE_DIR, "results.csv")
PLOT_DIR = os.path.join(BASE_DIR, "plots")
os.makedirs(PLOT_DIR, exist_ok=True)

# --- 3. LOAD & FILTER DATA ---
df = pd.read_csv(CSV_PATH)
df = df[df['confidence'] > 0.5].reset_index(drop=True)
df['path'] = df['clip'].apply(lambda x: os.path.join(AUDIO_DIR, x))
df = df[df['path'].apply(os.path.exists)]

emotions = sorted(df['emotion'].unique())
label2id = {label: i for i, label in enumerate(emotions)}
id2label = {i: label for label, i in label2id.items()}
df['label'] = df['emotion'].map(label2id)

dataset = Dataset.from_pandas(df[['path', 'label']]).train_test_split(test_size=0.2, seed=42)


# --- 5. FEATURE EXTRACTION ---
model_name = "superb/hubert-base-superb-er"
feature_extractor = Wav2Vec2FeatureExtractor.from_pretrained(model_name)

def preprocess(batch):
    audio_array, _ = librosa.load(batch["path"], sr=16000)
    features = feature_extractor(
        audio_array,
        sampling_rate=16000,
        padding="max_length",
        max_length=int(16000 * 15),
        truncation=True,
        return_attention_mask=True,
        return_tensors="pt"
    )
    batch["input_values"] = features["input_values"][0]
    batch["labels"] = batch["label"]
    if "attention_mask" in features:
        batch["attention_mask"] = features["attention_mask"][0]
    return batch

dataset_prep = dataset.map(preprocess, remove_columns=dataset["train"].column_names)
# --- 6. MODEL ---
model = HubertForSequenceClassification.from_pretrained(
    model_name,
    num_labels=len(emotions),
    label2id=label2id,
    id2label=id2label,
)


class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(df['label']),
    y=df['label']
)
class_weights = torch.tensor(class_weights, dtype=torch.float).to(model.device)
print("Class Weights:", class_weights)


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
class_weights = class_weights.to(device)

class WeightedTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, num_items_in_batch= None):
        labels = inputs.pop("labels")
        outputs = model(**inputs)
        logits = outputs.logits


        loss = F.cross_entropy(logits, labels, weight=class_weights)

        return (loss, outputs) if return_outputs else loss



# --- 7. METRICS FUNCTION ---
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    if isinstance(logits, tuple):
        logits = logits[0]
    predictions = np.argmax(logits, axis=1)
    return {"accuracy": accuracy_score(labels, predictions)}

# --- 8. TRAINING ARGS ---
training_args = TrainingArguments(
    output_dir=os.path.join(BASE_DIR, "hubert_emotion_finetuned"),
    per_device_train_batch_size=2,
    num_train_epochs=3,
    learning_rate=1e-5,
    weight_decay=0.01,
    eval_strategy="steps",
    save_strategy="steps",
    save_steps=250,
    eval_steps=250,
    logging_steps=250,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    disable_tqdm=False,
    per_device_eval_batch_size=1,
    fp16=True,
    eval_accumulation_steps=8,

)

# --- 9. TRAINER ---
trainer = WeightedTrainer(
    model=model,
    args=training_args,
    train_dataset=dataset_prep['train'],
    eval_dataset=dataset_prep['test'],
    tokenizer=feature_extractor,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]
)

# --- 10. CUSTOM CALLBACK FOR TRAIN ACCURACY ---
class TrainMetricsCallback(TrainerCallback):
    def __init__(self, trainer, dataset_prep, eval_subset_size=100):
        self.trainer = trainer

        self.train_subset = dataset_prep['train'].select(
            range(min(eval_subset_size, len(dataset_prep['train'])))
        )

    def on_log(self, args, state, control, logs=None, **kwargs):
        if logs is None or "loss" not in logs:
            return


        predictions = self.trainer.predict(self.train_subset)
        logits = predictions.predictions
        if isinstance(logits, tuple):
            logits = logits[0]
        y_pred = np.argmax(logits, axis=1)
        y_true = predictions.label_ids
        acc = (y_pred == y_true).mean()


        logs["training_accuracy"] = acc
        print(f"Step {state.global_step}: "
              f"Train Loss {logs['loss']:.4f} | Train Acc {acc:.4f}")


        self.trainer.state.log_history.append({**logs, "step": state.global_step})


trainer.add_callback(TrainMetricsCallback(trainer, dataset_prep))

trainer.add_callback(EarlyStoppingCallback(early_stopping_patience=2))

# --- 11. TRAIN MODEL ---
trainer.train()

# --- 9. LOGS ---
logs = pd.DataFrame(trainer.state.log_history)
if not logs.empty:
    print("\nTraining Logs:")
    print(logs[['step', 'loss', 'eval_loss', 'training_accuracy', 'eval_accuracy']])
else:
    print("No logs were recorded.")


logs = pd.DataFrame(trainer.state.log_history)
print(logs.head(20))

# --- PLOT TRAINING VS VALIDATION LOSS & ACCURACY ---
logs = pd.DataFrame(trainer.state.log_history)


# --- 10. EVALUATION ---
preds = trainer.predict(dataset_prep['test'])
logits = preds.predictions
if isinstance(logits, (tuple, list)):
    logits = logits[0]
if logits.ndim > 2:
    logits = logits.squeeze()
y_pred = np.argmax(logits, axis=1)
y_true = preds.label_ids

report = classification_report(y_true, y_pred, target_names=emotions, digits=3)
print("\nClassification Report:\n", report)

# Confusion Matrix
cm = confusion_matrix(y_true, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=emotions)
disp.plot(xticks_rotation=45)
plt.title("Confusion Matrix")
plt.show()


# --- 12. CONFIDENCE DISTRIBUTION FOR PREDICTIONS ---
probs = F.softmax(torch.tensor(logits), dim=1).numpy()
conf_correct = [max(probs[i]) for i in range(len(y_true)) if y_true[i] == y_pred[i]]
conf_wrong = [max(probs[i]) for i in range(len(y_true)) if y_true[i] != y_pred[i]]

plt.hist(conf_correct, bins=20, alpha=0.7, label='Correct')
plt.hist(conf_wrong, bins=20, alpha=0.7, label='Incorrect')
plt.xlabel("Confidence")
plt.ylabel("Frequency")
plt.title("Confidence Distribution")
plt.legend()
plt.show()



"""4.CNN

"""

pip install torchmetrics

pip install torchaudio --quiet

# === CNN TRAIN & SAVE (Colab) ===
from google.colab import drive
drive.mount('/content/drive')

import os, json, random, gc
import numpy as np
import pandas as pd
import torch, torch.nn as nn, torch.nn.functional as F, torch.optim as optim
import torchaudio, torchaudio.transforms as T
import matplotlib.pyplot as plt

from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
from sklearn.utils.class_weight import compute_class_weight
from torchmetrics.classification import Accuracy


gc.collect()
if torch.cuda.is_available():
    torch.cuda.empty_cache()
SEED = 42
random.seed(SEED); np.random.seed(SEED); torch.manual_seed(SEED)
if torch.cuda.is_available(): torch.cuda.manual_seed_all(SEED)
os.environ["WANDB_DISABLED"] = "true"

# ---- paths ----
BASE_DIR  = "/content/drive/MyDrive/Youtube_Emotion_Project"
AUDIO_DIR = os.path.join(BASE_DIR, "audio_segments")
CSV_PATH  = os.path.join(BASE_DIR, "results.csv")

OUT_DIR  = os.path.join(BASE_DIR, "cnn_runs")
PLOT_DIR = os.path.join(OUT_DIR, "plots")
os.makedirs(OUT_DIR, exist_ok=True)
os.makedirs(PLOT_DIR, exist_ok=True)

# ---- load data ----
df = pd.read_csv(CSV_PATH)
df = df[df['confidence'] > 0.5].reset_index(drop=True)
df['path'] = df['clip'].apply(lambda x: os.path.join(AUDIO_DIR, x))
df = df[df['path'].apply(os.path.exists)].reset_index(drop=True)

emotions = sorted(df['emotion'].unique())
label2id = {e:i for i, e in enumerate(emotions)}
id2label = {i:e for e,i in zip(emotions, range(len(emotions)))}
df['label'] = df['emotion'].map(label2id)

print(f"Dataset size: {len(df)}")
print("Emotions:", emotions)

# save labels mapping for inference
with open(os.path.join(OUT_DIR, "labels.json"), "w") as f:
    json.dump({"emotions": emotions, "label2id": label2id, "id2label": id2label}, f, indent=2)

# ---- split ----
train_df, val_df = train_test_split(df, test_size=0.2, stratify=df['label'], random_state=SEED)

# ---- dataset ----
N_MELS = 64
MAX_LEN = 128

class AudioDataset(Dataset):
    def __init__(self, df, emotions, train=False):
        self.df = df.reset_index(drop=True)
        self.emotions = emotions
        self.train = train
        self.mel = torchaudio.transforms.MelSpectrogram(sample_rate=16000, n_mels=N_MELS)
        self.to_db = T.AmplitudeToDB()
        self.t_mask = T.TimeMasking(time_mask_param=10)
        self.f_mask = T.FrequencyMasking(freq_mask_param=5)

    def __len__(self): return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        wav, sr = torchaudio.load(row['path'])
        if sr != 16000:
            wav = torchaudio.functional.resample(wav, sr, 16000)

        mel = self.mel(wav)
        mel_db = self.to_db(mel)


        mel_db = (mel_db - mel_db.mean()) / (mel_db.std() + 1e-6)


        if self.train:
            if random.random() < 0.5: mel_db = self.t_mask(mel_db)
            if random.random() < 0.5: mel_db = self.f_mask(mel_db)


        Tlen = mel_db.shape[-1]
        if Tlen > MAX_LEN:
            mel_db = mel_db[:, :, :MAX_LEN]
        else:
            mel_db = F.pad(mel_db, (0, MAX_LEN - Tlen))

        label = self.emotions.index(row['emotion'])
        return mel_db, label

def collate_fn(batch):
    mels, labels = zip(*batch)
    max_len = max(m.shape[-1] for m in mels)
    mels = [F.pad(m, (0, max_len - m.shape[-1])) for m in mels]
    return torch.stack(mels), torch.tensor(labels)

class AudioCNN(nn.Module):
    def __init__(self, num_classes):
        super().__init__()
        self.cnn = nn.Sequential(

            nn.Conv1d(N_MELS, 16, 3, padding=1), nn.BatchNorm1d(16), nn.ReLU(), nn.MaxPool1d(2), nn.Dropout(0.2),
            nn.Conv1d(16, 32, 3, padding=1),     nn.BatchNorm1d(32), nn.ReLU(), nn.MaxPool1d(2), nn.Dropout(0.2),
            nn.Conv1d(32, 64, 3, padding=1),     nn.BatchNorm1d(64), nn.ReLU(), nn.MaxPool1d(2), nn.Dropout(0.3),
            nn.Conv1d(64, 128, 3, padding=1),    nn.BatchNorm1d(128), nn.ReLU(),
            nn.AdaptiveAvgPool1d(4),
        )
        self.fc = nn.Sequential(
            nn.Flatten(),
            nn.Linear(128*4, 256), nn.ReLU(), nn.Dropout(0.4),
            nn.Linear(256, num_classes)
        )

    def forward(self, x):
        x = x.squeeze(1)
        x = self.cnn(x)
        return self.fc(x)


device = 'cuda' if torch.cuda.is_available() else 'cpu'
print("Device:", device)

train_ds = AudioDataset(train_df, emotions, train=True)
val_ds   = AudioDataset(val_df,   emotions, train=False)
train_loader = DataLoader(train_ds, batch_size=32, shuffle=True,  collate_fn=collate_fn, num_workers=2, pin_memory=(device=='cuda'))
val_loader   = DataLoader(val_ds,   batch_size=32, shuffle=False, collate_fn=collate_fn, num_workers=2, pin_memory=(device=='cuda'))


class_weights = compute_class_weight('balanced', classes=np.unique(train_df['label']), y=train_df['label'])
class_weights = torch.tensor(class_weights, dtype=torch.float32, device=device)
print("Class weights:", class_weights.tolist())

model = AudioCNN(num_classes=len(emotions)).to(device)
criterion = nn.CrossEntropyLoss(weight=class_weights)
optimizer = optim.Adam(model.parameters(), lr=1e-3)
scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, patience=2)

train_acc_metric = Accuracy(task='multiclass', num_classes=len(emotions)).to(device)
val_acc_metric   = Accuracy(task='multiclass', num_classes=len(emotions)).to(device)

EPOCHS = 4
BEST_PATH = os.path.join(OUT_DIR, "cnn_emotion_model_best.pth")
LAST_PATH = os.path.join(OUT_DIR, "cnn_emotion_model_last.pth")

best_val_acc = 0.0
train_acc_hist, val_acc_hist = [], []
train_loss_hist, val_loss_hist = [], []

for ep in range(EPOCHS):
    # train
    model.train()
    train_acc_metric.reset()
    total_loss = 0.0
    for mel, y in train_loader:
        mel, y = mel.to(device, non_blocking=True), y.to(device, non_blocking=True)
        optimizer.zero_grad()
        logits = model(mel)
        loss = criterion(logits, y)
        loss.backward(); optimizer.step()
        total_loss += loss.item()
        train_acc_metric.update(logits, y)

    train_loss = total_loss / len(train_loader)
    train_acc  = train_acc_metric.compute().item()
    train_loss_hist.append(train_loss); train_acc_hist.append(train_acc)

    # validate
    model.eval()
    val_acc_metric.reset()
    val_loss = 0.0
    y_true, y_pred = [], []
    conf_scores = []
    with torch.no_grad():
        for mel, y in val_loader:
            mel, y = mel.to(device, non_blocking=True), y.to(device, non_blocking=True)
            logits = model(mel)
            loss = criterion(logits, y)
            val_loss += loss.item()
            val_acc_metric.update(logits, y)
            pred = logits.argmax(dim=1)
            y_true.extend(y.cpu().numpy().tolist())
            y_pred.extend(pred.cpu().numpy().tolist())
            probs = torch.softmax(logits, dim=1)
            conf_scores.extend(probs.max(dim=1).values.cpu().tolist())

    val_loss /= len(val_loader)
    val_acc = val_acc_metric.compute().item()
    val_loss_hist.append(val_loss); val_acc_hist.append(val_acc)
    scheduler.step(val_loss)

    if val_acc > best_val_acc:
        best_val_acc = val_acc
        torch.save(model.state_dict(), BEST_PATH)

    print(f"Epoch {ep+1}/{EPOCHS}  "
          f"Train Loss {train_loss:.4f} Acc {train_acc:.4f} | "
          f"Val Loss {val_loss:.4f} Acc {val_acc:.4f}")

# save last
torch.save(model.state_dict(), LAST_PATH)
print("\nSaved:", LAST_PATH)
print("Best (by Val Acc):", BEST_PATH)

# plots
plt.figure(); plt.plot(train_acc_hist, label='Train'); plt.plot(val_acc_hist, label='Val')
plt.title("Accuracy"); plt.xlabel("Epoch"); plt.ylabel("Acc"); plt.legend()
plt.savefig(os.path.join(PLOT_DIR, "accuracy_curve.png"), bbox_inches='tight'); plt.show()

plt.figure(); plt.plot(train_loss_hist, label='Train'); plt.plot(val_loss_hist, label='Val')
plt.title("Loss"); plt.xlabel("Epoch"); plt.ylabel("Loss"); plt.legend()
plt.savefig(os.path.join(PLOT_DIR, "loss_curve.png"), bbox_inches='tight'); plt.show()

print("\nClassification report on validation:")
print(classification_report(y_true, y_pred, target_names=emotions, digits=3))

cm = confusion_matrix(y_true, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=emotions)
disp.plot(xticks_rotation=45); plt.title("Confusion Matrix (Val)")
plt.savefig(os.path.join(PLOT_DIR, "confusion_matrix_val.png"), bbox_inches='tight'); plt.show()

# --- CONFIDENCE DISTRIBUTION FOR PREDICTIONS ---
conf_correct = [c for c, yt, yp in zip(conf_scores, y_true, y_pred) if yt == yp]
conf_wrong   = [c for c, yt, yp in zip(conf_scores, y_true, y_pred) if yt != yp]

plt.figure()
plt.hist(conf_correct, bins=20, alpha=0.7, label='Correct')
plt.hist(conf_wrong,   bins=20, alpha=0.7, label='Incorrect')
plt.xlabel("Confidence")
plt.ylabel("Frequency")
plt.title("Confidence Distribution")
plt.legend()
plt.savefig(os.path.join(PLOT_DIR, "confidence_distribution.png"), bbox_inches='tight')
plt.show()



print("\nAll CNN artifacts saved under:", OUT_DIR)

# --- SETUP ---
from google.colab import drive
drive.mount('/content/drive', force_remount=False)

import os, sys, subprocess, requests
import numpy as np
import soundfile as sf
import librosa
import torch
import matplotlib.pyplot as plt


def pip_install(p): subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", p])

try:
    from transformers import AutoFeatureExtractor, AutoModelForAudioClassification
except:
    pip_install("transformers>=4.40.0")
    from transformers import AutoFeatureExtractor, AutoModelForAudioClassification

try:
    import yt_dlp
except:
    pip_install("yt-dlp"); import yt_dlp

# --- CONFIG: best HuBERT checkpoint ---
HUBERT_PATH = "/content/drive/MyDrive/Youtube_Emotion_Project/hubert_emotion_finetuned/checkpoint-750"
TARGET_SR = 16000


WINDOW_SEC = 20
HOP_SEC    = 10
AUDIO_OUT  = "/content/user_audio.wav"

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# --- DOWNLOAD AUDIO ---
def download_video_audio_to_wav(url, out_wav):
    if "youtube.com" in url or "youtu.be" in url:
        ydl_opts = {
            'format': 'bestaudio/best',
            'outtmpl': 'temp_audio.%(ext)s',
            'postprocessors': [{'key': 'FFmpegExtractAudio','preferredcodec': 'wav','preferredquality': '192'}],
            'quiet': True,
        }
        with yt_dlp.YoutubeDL(ydl_opts) as ydl: ydl.download([url])
        raw_wav = "temp_audio.wav"
        cmd = ["ffmpeg", "-y", "-i", raw_wav, "-ac", "1", "-ar", str(TARGET_SR), out_wav]
        subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        os.remove(raw_wav)
    elif "drive.google.com" in url:
        if "id=" in url: file_id = url.split("id=")[1]
        elif "/d/" in url: file_id = url.split("/d/")[1].split("/")[0]
        else: raise ValueError("Invalid Google Drive link.")
        r = requests.get(f"https://drive.google.com/uc?export=download&id={file_id}")
        with open("temp_drive_file", "wb") as f: f.write(r.content)
        cmd = ["ffmpeg", "-y", "-i", "temp_drive_file", "-ac", "1", "-ar", str(TARGET_SR), out_wav]
        subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        os.remove("temp_drive_file")
    else:
        raise ValueError("Provide a YouTube or Google Drive link.")
    print(f"✅ Audio saved to {out_wav}")

def label_from_mapping(id2label, idx):
    if isinstance(id2label, dict):
        return id2label.get(str(idx), id2label.get(idx, str(idx)))
    return str(idx)

# --- LOAD BEST HUBERT ---
print(f"\n🔎 Loading HuBERT from: {HUBERT_PATH}")
fe  = AutoFeatureExtractor.from_pretrained(HUBERT_PATH, local_files_only=True)
model = AutoModelForAudioClassification.from_pretrained(HUBERT_PATH, local_files_only=True).to(device).eval()
id2label = getattr(model.config, "id2label", {})
num_classes = len(id2label) if isinstance(id2label, dict) else model.config.num_labels

# --- EMOTION over FULL AUDIO  ---
def predict_emotion_window(wave_1d, sr, window_sec):
    """Return probs for a single window (resamples/pads/truncates to window length)."""
    if sr != TARGET_SR:
        wave_1d = librosa.resample(wave_1d, orig_sr=sr, target_sr=TARGET_SR)
        sr = TARGET_SR

    max_len_samples = int(window_sec * sr)

    if len(wave_1d) < max_len_samples:
        pad = max_len_samples - len(wave_1d)
        wave_1d = np.pad(wave_1d, (0, pad), mode="constant")
    else:
        wave_1d = wave_1d[:max_len_samples]

    inputs = fe(wave_1d, sampling_rate=sr, return_tensors="pt")
    inputs = {k: v.to(device) for k, v in inputs.items()}
    with torch.no_grad():
        logits = model(**inputs).logits
        probs  = torch.softmax(logits, dim=-1).squeeze(0).detach().cpu().numpy()
    return probs

def sliding_window_predict(wav_path, window_sec=WINDOW_SEC, hop_sec=HOP_SEC, aggregate="mean", show_plot=True, save_csv=True):
    """Runs emotion prediction over the full audio using sliding windows."""
    audio, sr = sf.read(wav_path)
    if isinstance(audio, np.ndarray) and audio.ndim > 1:
        audio = audio.mean(axis=1)
    if sr != TARGET_SR:
        audio = librosa.resample(audio, orig_sr=sr, target_sr=TARGET_SR)
        sr = TARGET_SR

    win = int(window_sec * sr)
    hop = int(hop_sec * sr)
    T   = len(audio)

    starts = list(range(0, max(T - win, 0) + 1, hop))
    if not starts:
        starts = [0]

    if starts[-1] + win < T:
        starts.append(T - win)

    all_probs = []
    time_stamps = []
    for s in starts:
        e = min(s + win, T)
        probs = predict_emotion_window(audio[s:e], sr, window_sec)
        all_probs.append(probs)
        time_stamps.append((s / sr, e / sr))

    all_probs = np.stack(all_probs, axis=0)


    if aggregate == "mean":
        agg_probs = all_probs.mean(axis=0)
    elif aggregate == "median":
        agg_probs = np.median(all_probs, axis=0)
    else:
        votes = np.argmax(all_probs, axis=1)
        agg_probs = np.zeros(num_classes, dtype=float)
        for v in votes: agg_probs[v] += 1.0
        agg_probs = agg_probs / agg_probs.sum()

    pred_id = int(np.argmax(agg_probs))
    label = label_from_mapping(id2label, pred_id)
    conf  = float(agg_probs[pred_id])

    print(f"\n🎯 Aggregated Emotion (full audio): {label} | Confidence: {conf:.4f} | Windows: {len(all_probs)}")


    if save_csv:
        import csv
        csv_path = "/content/emotion_timeline.csv"
        labels = [label_from_mapping(id2label, i) for i in range(num_classes)]
        with open(csv_path, "w", newline="") as f:
            writer = csv.writer(f)
            writer.writerow(["start_sec", "end_sec"] + labels + ["pred_label"])
            for (st, en), p in zip(time_stamps, all_probs):
                writer.writerow([round(st,2), round(en,2), *[round(x,4) for x in p], label_from_mapping(id2label, int(np.argmax(p)))])
        print(f"📝 Per-window timeline saved: {csv_path}")


    if show_plot:
        labels = [label_from_mapping(id2label, i) for i in range(num_classes)]
        topk = min(4, num_classes)

        x = [ (st+en)/2.0 for (st,en) in time_stamps ]
        plt.figure(figsize=(10,4))
        for cls_id in range(num_classes):
            plt.plot(x, all_probs[:, cls_id], alpha=0.6, label=labels[cls_id])
        plt.xlabel("Time (s)")
        plt.ylabel("Probability")
        plt.title("Emotion Probabilities over Time (sliding windows)")
        plt.ylim(0,1); plt.grid(True, linestyle="--", alpha=0.4); plt.legend(bbox_to_anchor=(1.02, 1), loc="upper left")
        plt.tight_layout(); plt.show()


        plt.figure(figsize=(7,4))
        plt.bar(labels, agg_probs)
        plt.title("Aggregated Emotion Probabilities (full audio)")
        plt.ylim(0,1); plt.grid(axis='y', linestyle='--', alpha=0.4)
        plt.xticks(rotation=30, ha="right")
        plt.tight_layout(); plt.show()

    return label, conf, all_probs, time_stamps

# --- TRANSCRIBE + SUMMARIZE ---
def transcribe_and_summarize(audio_path, best_model="HuBERT", best_emotion=None, best_conf=None, language="en"):
    try:
        import whisper
    except ImportError:
        pip_install("openai-whisper"); import whisper
    try:
        from transformers import pipeline
    except ImportError:
        pip_install("transformers"); from transformers import pipeline

    print("\n🗣️ Transcribing audio (Whisper small)...")
    w = whisper.load_model("small")
    result = w.transcribe(audio_path, language=language)
    text = (result.get("text") or "").strip()
    print(f"Transcript length: {len(text)} chars")
    if not text:
        print("No speech detected.")
        return ""

    print("🧾 Summarizing transcript...")
    summarizer = pipeline("summarization", model="sshleifer/distilbart-cnn-12-6")
    max_chunk = 1000
    chunks = [text[i:i+max_chunk] for i in range(0, len(text), max_chunk)]
    parts = [summarizer(c, max_length=130, min_length=30, do_sample=False)[0]["summary_text"] for c in chunks]
    summary = " ".join(parts)

    save_path = "audio_summary.txt"
    with open(save_path, "w", encoding="utf-8") as f:
        f.write(f"Best Model: {best_model}\n")
        if best_emotion: f.write(f"Detected Emotion: {best_emotion}\n")
        if best_conf:    f.write(f"Confidence: {best_conf:.4f}\n")
        f.write("\n--- Transcript Summary ---\n")
        f.write(summary)

    print("\n--- SUMMARY ---\n", summary)
    print(f"📄 Summary saved to {save_path}")
    return summary

# --- MAIN ---
video_url = input("Paste a YouTube or Google Drive video link here: ").strip()
download_video_audio_to_wav(video_url, AUDIO_OUT)

best_emotion, best_conf, window_probs, time_stamps = sliding_window_predict(
    AUDIO_OUT,
    window_sec=WINDOW_SEC,
    hop_sec=HOP_SEC,
    aggregate="mean",
    show_plot=True,
    save_csv=True
)
print("\n✅ Final detected emotion (full audio):", best_emotion, f"({best_conf:.3f})")

ans = input("\nDo you want a short summary of the audio? (y/n): ").strip().lower()
if ans == "y":
    _ = transcribe_and_summarize(
        AUDIO_OUT,
        best_model="HuBERT",
        best_emotion=best_emotion,
        best_conf=best_conf,
    )

import gradio, websockets, platform
print("Python:", platform.python_version())
print("gradio:", gradio.__version__)
print("websockets:", websockets.__version__)

# --- SETUP ---
from google.colab import drive
drive.mount('/content/drive', force_remount=False)

import os, sys, subprocess, requests
import numpy as np
import soundfile as sf
import librosa
import torch
import matplotlib.pyplot as plt


RUN_GRADIO = True


def pip_install(p): subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", p])

try:
    from transformers import AutoFeatureExtractor, AutoModelForAudioClassification
except:
    pip_install("transformers>=4.40.0")
    from transformers import AutoFeatureExtractor, AutoModelForAudioClassification

try:
    import yt_dlp
except:
    pip_install("yt-dlp"); import yt_dlp

# --- CONFIG: HuBERT ---
HUBERT_PATH = "/content/drive/MyDrive/Youtube_Emotion_Project/hubert_emotion_finetuned/checkpoint-750"  # <-- your best
TARGET_SR = 16000


WINDOW_SEC = 20
HOP_SEC    = 10
AUDIO_OUT  = "/content/user_audio.wav"

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# --- DOWNLOAD AUDIO ---
def download_video_audio_to_wav(url, out_wav):
    if "youtube.com" in url or "youtu.be" in url:
        ydl_opts = {
            'format': 'bestaudio/best',
            'outtmpl': 'temp_audio.%(ext)s',
            'postprocessors': [{'key': 'FFmpegExtractAudio','preferredcodec': 'wav','preferredquality': '192'}],
            'quiet': True,
        }
        with yt_dlp.YoutubeDL(ydl_opts) as ydl: ydl.download([url])
        raw_wav = "temp_audio.wav"
        cmd = ["ffmpeg", "-y", "-i", raw_wav, "-ac", "1", "-ar", str(TARGET_SR), out_wav]
        subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        os.remove(raw_wav)
    elif "drive.google.com" in url:
        if "id=" in url: file_id = url.split("id=")[1]
        elif "/d/" in url: file_id = url.split("/d/")[1].split("/")[0]
        else: raise ValueError("Invalid Google Drive link.")
        r = requests.get(f"https://drive.google.com/uc?export=download&id={file_id}")
        with open("temp_drive_file", "wb") as f: f.write(r.content)
        cmd = ["ffmpeg", "-y", "-i", "temp_drive_file", "-ac", "1", "-ar", str(TARGET_SR), out_wav]
        subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        os.remove("temp_drive_file")
    else:
        raise ValueError("Provide a YouTube or Google Drive link.")
    print(f"✅ Audio saved to {out_wav}")

def label_from_mapping(id2label, idx):
    if isinstance(id2label, dict):
        return id2label.get(str(idx), id2label.get(idx, str(idx)))
    return str(idx)

# --- LOAD BEST HUBERT ---
print(f"\n🔎 Loading HuBERT from: {HUBERT_PATH}")
fe  = AutoFeatureExtractor.from_pretrained(HUBERT_PATH, local_files_only=True)
model = AutoModelForAudioClassification.from_pretrained(HUBERT_PATH, local_files_only=True).to(device).eval()
id2label = getattr(model.config, "id2label", {})
num_classes = len(id2label) if isinstance(id2label, dict) else model.config.num_labels

# --- EMOTION over FULL AUDIO ---
def predict_emotion_window(wave_1d, sr, window_sec):
    """Return probs for a single window (resamples/pads/truncates to window length)."""
    if sr != TARGET_SR:
        wave_1d = librosa.resample(wave_1d, orig_sr=sr, target_sr=TARGET_SR)
        sr = TARGET_SR

    max_len_samples = int(window_sec * sr)

    if len(wave_1d) < max_len_samples:
        pad = max_len_samples - len(wave_1d)
        wave_1d = np.pad(wave_1d, (0, pad), mode="constant")
    else:
        wave_1d = wave_1d[:max_len_samples]

    inputs = fe(wave_1d, sampling_rate=sr, return_tensors="pt")
    inputs = {k: v.to(device) for k, v in inputs.items()}
    with torch.no_grad():
        logits = model(**inputs).logits
        probs  = torch.softmax(logits, dim=-1).squeeze(0).detach().cpu().numpy()
    return probs

def sliding_window_predict(wav_path, window_sec=WINDOW_SEC, hop_sec=HOP_SEC, aggregate="mean", show_plot=True, save_csv=True):
    """Runs emotion prediction over the full audio using sliding windows."""
    audio, sr = sf.read(wav_path)
    if isinstance(audio, np.ndarray) and audio.ndim > 1:
        audio = audio.mean(axis=1)
    if sr != TARGET_SR:
        audio = librosa.resample(audio, orig_sr=sr, target_sr=TARGET_SR)
        sr = TARGET_SR

    win = int(window_sec * sr)
    hop = int(hop_sec * sr)
    T   = len(audio)

    starts = list(range(0, max(T - win, 0) + 1, hop))
    if not starts:
        starts = [0]

    if starts[-1] + win < T:
        starts.append(T - win)

    all_probs = []
    time_stamps = []
    for s in starts:
        e = min(s + win, T)
        probs = predict_emotion_window(audio[s:e], sr, window_sec)
        all_probs.append(probs)
        time_stamps.append((s / sr, e / sr))

    all_probs = np.stack(all_probs, axis=0)


    if aggregate == "mean":
        agg_probs = all_probs.mean(axis=0)
    elif aggregate == "median":
        agg_probs = np.median(all_probs, axis=0)
    else:
        votes = np.argmax(all_probs, axis=1)
        agg_probs = np.zeros(num_classes, dtype=float)
        for v in votes: agg_probs[v] += 1.0
        s = agg_probs.sum()
        agg_probs = agg_probs / (s if s else 1.0)

    pred_id = int(np.argmax(agg_probs))
    label = label_from_mapping(id2label, pred_id)
    conf  = float(agg_probs[pred_id])

    print(f"\n🎯 Aggregated Emotion (full audio): {label} | Confidence: {conf:.4f} | Windows: {len(all_probs)}")

    if save_csv:
        import csv
        csv_path = "/content/emotion_timeline.csv"
        labels = [label_from_mapping(id2label, i) for i in range(num_classes)]
        with open(csv_path, "w", newline="") as f:
            writer = csv.writer(f)
            writer.writerow(["start_sec", "end_sec"] + labels + ["pred_label"])
            for (st, en), p in zip(time_stamps, all_probs):
                writer.writerow([round(st,2), round(en,2), *[round(x,4) for x in p], label_from_mapping(id2label, int(np.argmax(p)))])
        print(f"📝 Per-window timeline saved: {csv_path}")


    if show_plot:
        labels = [label_from_mapping(id2label, i) for i in range(num_classes)]
        x = [ (st+en)/2.0 for (st,en) in time_stamps ]
        plt.figure(figsize=(10,4))
        for cls_id in range(num_classes):
            plt.plot(x, all_probs[:, cls_id], alpha=0.6, label=labels[cls_id])
        plt.xlabel("Time (s)")
        plt.ylabel("Probability")
        plt.title("Emotion Probabilities over Time (sliding windows)")
        plt.ylim(0,1); plt.grid(True, linestyle="--", alpha=0.4); plt.legend(bbox_to_anchor=(1.02, 1), loc="upper left")
        plt.tight_layout(); plt.show()

        # Aggregated bar chart
        plt.figure(figsize=(7,4))
        plt.bar(labels, agg_probs)
        plt.title("Aggregated Emotion Probabilities (full audio)")
        plt.ylim(0,1); plt.grid(axis='y', linestyle='--', alpha=0.4)
        plt.xticks(rotation=30, ha="right")
        plt.tight_layout(); plt.show()

    return label, conf, all_probs, time_stamps

# --- TRANSCRIBE + SUMMARIZE ---
def transcribe_and_summarize(audio_path, best_model="HuBERT", best_emotion=None, best_conf=None, language="en"):
    try:
        import whisper
    except ImportError:
        pip_install("openai-whisper"); import whisper
    try:
        from transformers import pipeline
    except ImportError:
        pip_install("transformers"); from transformers import pipeline

    print("\n🗣️ Transcribing audio (Whisper small)...")
    w = whisper.load_model("small")
    result = w.transcribe(audio_path, language=language)
    text = (result.get("text") or "").strip()
    print(f"Transcript length: {len(text)} chars")
    if not text:
        print("No speech detected.")
        return ""

    print("🧾 Summarizing transcript...")
    summarizer = pipeline("summarization", model="sshleifer/distilbart-cnn-12-6")
    max_chunk = 1000
    chunks = [text[i:i+max_chunk] for i in range(0, len(text), max_chunk)]
    parts = [summarizer(c, max_length=130, min_length=30, do_sample=False)[0]["summary_text"] for c in chunks]
    summary = " ".join(parts)

    save_path = "audio_summary.txt"
    with open(save_path, "w", encoding="utf-8") as f:
        f.write(f"Best Model: {best_model}\n")
        if best_emotion: f.write(f"Detected Emotion: {best_emotion}\n")
        if best_conf is not None: f.write(f"Confidence: {best_conf:.4f}\n")
        f.write("\n--- Transcript Summary ---\n")
        f.write(summary)

    print("\n--- SUMMARY ---\n", summary)
    print(f"📄 Summary saved to {save_path}")
    return summary

# ---------------- GRADIO APP (live demo) ----------------
if RUN_GRADIO:

    import gradio as gr
    from pathlib import Path

    def run_pipeline(url, do_summary=False):
        """Full pipeline: download -> predict -> plots -> (optional) transcribe & summarize."""
        aggregate = "mean"
        try:
            # 1) download audio
            out_wav = AUDIO_OUT
            download_video_audio_to_wav(url, out_wav)

            # 2) run sliding-window prediction
            label, conf, all_probs, time_stamps = sliding_window_predict(
                out_wav,
                window_sec=WINDOW_SEC,
                hop_sec=HOP_SEC,
                aggregate=aggregate,
                show_plot=False,
                save_csv=True
            )

            labels = [label_from_mapping(id2label, i) for i in range(len(all_probs[0]))]
            x = [ (st+en)/2.0 for (st,en) in time_stamps ]

            # 3) timeline plot
            fig1 = plt.figure(figsize=(10,4))
            for cls_id in range(len(labels)):
                plt.plot(x, all_probs[:, cls_id], alpha=0.8, label=labels[cls_id])
            plt.xlabel("Time (s)")
            plt.ylabel("Probability")
            plt.ylim(0,1)
            plt.title("Emotion Probabilities over Time (sliding windows)")
            plt.grid(True, linestyle="--", alpha=0.4)
            plt.legend(loc="upper right")
            plt.tight_layout()

            # 4) aggregated bar chart (mean)
            agg_probs = all_probs.mean(axis=0)
            fig2 = plt.figure(figsize=(7,4))
            plt.bar(labels, agg_probs)
            plt.title("Aggregated Emotion Probabilities (full audio)")
            plt.ylim(0,1)
            plt.grid(axis='y', linestyle='--', alpha=0.4)
            plt.xticks(rotation=30, ha="right")
            plt.tight_layout()

            # 5) transcript + summary
            summary_text = ""
            summary_file = None
            if do_summary:
                summary_text = transcribe_and_summarize(
                    AUDIO_OUT,
                    best_model="HuBERT",
                    best_emotion=label,
                    best_conf=conf,
                )
                summary_file = Path("audio_summary.txt").as_posix()

            # 6) return everything to the UI
            csv_path = "/content/emotion_timeline.csv"
            headline = f"Detected emotion: {label}  (confidence: {conf:.3f})"
            return headline, fig1, fig2, (csv_path if Path(csv_path).exists() else None), summary_text, (summary_file if summary_file else None)

        except Exception as e:
            msg = f"❌ Error: {type(e).__name__}: {e}"
            return msg, None, None, None, "", None

    with gr.Blocks(title="SER + ASR Demo") as demo:
        gr.Markdown("# 🎤 Speech Emotion Recognition (Live Demo)")
        with gr.Row():
            url = gr.Textbox(
                label="YouTube or Google Drive link",
                placeholder="https://youtu.be/... or https://drive.google.com/file/d/..."
            )
        # summarization toggle
        with gr.Row():
            do_summary = gr.Checkbox(
                value=False,
                label="Also transcribe & summarize (Whisper + DistilBART)"
            )

        run_btn = gr.Button("Run pipeline")
        headline = gr.Markdown("")
        fig_timeline = gr.Plot(label="Emotion timeline")
        fig_bar = gr.Plot(label="Aggregated probabilities")
        csv_file = gr.File(label="Per-window CSV (download)", interactive=False)
        summary_out = gr.Textbox(label="Transcript summary", lines=8)
        summary_file = gr.File(label="Summary file", interactive=False)

        run_btn.click(
            fn=run_pipeline,
            inputs=[url, do_summary],
            outputs=[headline, fig_timeline, fig_bar, csv_file, summary_out, summary_file],
            queue=True
        )

    demo.queue().launch(share=True)

# ---------------- MAIN (CLI mode) ----------------
if not RUN_GRADIO:
    # --- MAIN ---
    video_url = input("Paste a YouTube or Google Drive video link here: ").strip()
    download_video_audio_to_wav(video_url, AUDIO_OUT)

    best_emotion, best_conf, window_probs, time_stamps = sliding_window_predict(
        AUDIO_OUT,
        window_sec=WINDOW_SEC,
        hop_sec=HOP_SEC,
        aggregate="mean",
        show_plot=True,
        save_csv=True
    )
    print("\n✅ Final detected emotion (full audio):", best_emotion, f"({best_conf:.3f})")

    ans = input("\nDo you want a short summary of the audio? (y/n): ").strip().lower()
    if ans == "y":
        _ = transcribe_and_summarize(
            AUDIO_OUT,
            best_model="HuBERT",
            best_emotion=best_emotion,

            best_conf=best_conf,
        )